name: Docker Image CI

on:
  schedule:
    - cron: 0 9 1 * *
  push:
    branches: 
    - "master"
    - "release/*"
  pull_request:
    branches: [ "master" ]

jobs:
  pull_request_build:
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'pull_request' && github.base_ref == 'master' }}

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag jumpbox:$(date +%s)

  build:
    runs-on: ubuntu-latest
    if: ${{ github.event_name != 'pull_request' }}

    steps:
    - uses: actions/checkout@v3

    # Deciding Docker image tag based on the git branch
    - name: Sets env vars for master
      run: echo "TAG_NAME=latest" >> $GITHUB_ENV
      if: ${{ github.ref == 'refs/heads/master' }}
    
    - name: Sets env vars for staging
      run: echo "TAG_NAME=18.04" >> $GITHUB_ENV
      if: ${{ github.ref == 'refs/heads/release/ubuntu-18.04' }}
    
    - name: Sets env vars for staging
      run: echo "TAG_NAME=20.04" >> $GITHUB_ENV
      if: ${{ github.ref == 'refs/heads/release/ubuntu-20.04' }}
    
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: Build and push
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: ${{ secrets.DOCKER_USERNAME }}/jumpbox:${{env.TAG_NAME}}