name: Docker Image CI

on:
  push:
    branches: [ "feature/github-action" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag jumpbox:$(date +%s)
